############################
# Target executable and files
############################
EXE = mesh
OBJ = mesh.o tensor.o util.o hexMesh.o mshMesh.o meshApp.o

#############################
# paths
############################
ALLDIR   = mesh tensor util
INC      =
LINC     =

#############################
# include
############################
include ../../Make.inc
